"""created events table

Revision ID: 80bfeb6aa7b2
Revises: 7b1096b8addd
Create Date: 2026-07-07 14:32:10.902871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80bfeb6aa7b2'
down_revision: Union[str, None] = '7b1096b8addd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organizer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'users', ['organizer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'organizer_id')
    # ### end Alembic commands ###
