"""add qr_code to tickets

Revision ID: 99e9b6aa388b
Revises: add7cea8b9d5
Create Date: 2026-07-16 10:01:31.057428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e9b6aa388b'
down_revision: Union[str, None] = 'add7cea8b9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('qr_code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'tickets', ['qr_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='unique')
    op.drop_column('tickets', 'qr_code')
    # ### end Alembic commands ###
